<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="9" failed="0" total="9" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="4367" started-at="2016-02-11T19:16:49Z" finished-at="2016-02-11T19:16:53Z">
    <groups>
      <group name="testNegativeDeleteAuthorWithNoBooks">
        <method signature="AuthorManagerTest.testNegativeDeleteAuthorWithNoBooks()[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84]" name="testNegativeDeleteAuthorWithNoBooks" class="com.softserveinc.booklibrary.test.manager.AuthorManagerTest"/>
      </group> <!-- testNegativeDeleteAuthorWithNoBooks -->
      <group name="createAuthor">
        <method signature="AuthorManagerTest.testCreateAuthor()[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84]" name="testCreateAuthor" class="com.softserveinc.booklibrary.test.manager.AuthorManagerTest"/>
        <method signature="AuthorManagerTest.testNegativeCreateAuthor(com.softserveinc.booklibrary.model.entity.Author)[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84]" name="testNegativeCreateAuthor" class="com.softserveinc.booklibrary.test.manager.AuthorManagerTest"/>
      </group> <!-- createAuthor -->
      <group name="updateAuthor">
        <method signature="AuthorManagerTest.testDeleteAuthor()[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84]" name="testDeleteAuthor" class="com.softserveinc.booklibrary.test.manager.AuthorManagerTest"/>
        <method signature="AuthorManagerTest.testNegativeDeleteAuthor(java.lang.String)[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84]" name="testNegativeDeleteAuthor" class="com.softserveinc.booklibrary.test.manager.AuthorManagerTest"/>
        <method signature="AuthorManagerTest.testBulkDeleteAuthor()[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84]" name="testBulkDeleteAuthor" class="com.softserveinc.booklibrary.test.manager.AuthorManagerTest"/>
      </group> <!-- updateAuthor -->
    </groups>
    <test name="Default test" duration-ms="4367" started-at="2016-02-11T19:16:49Z" finished-at="2016-02-11T19:16:53Z">
      <class name="com.softserveinc.booklibrary.test.manager.AuthorManagerTest">
        <test-method status="PASS" signature="arquillianBeforeSuite()[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84]" name="arquillianBeforeSuite" is-config="true" duration-ms="680" started-at="2016-02-11T21:16:48Z" finished-at="2016-02-11T21:16:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- arquillianBeforeSuite -->
        <test-method status="FAIL" signature="arquillianBeforeClass()[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84]" name="arquillianBeforeClass" is-config="true" duration-ms="0" started-at="2016-02-11T21:16:49Z" finished-at="2016-02-11T21:16:49Z">
          <exception class="org.jboss.arquillian.container.spi.client.container.DeploymentException">
            <message>
              <![CDATA[Cannot deploy: authorManager.war]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.jboss.arquillian.container.spi.client.container.DeploymentException: Cannot deploy: authorManager.war
	at org.jboss.as.arquillian.container.ArchiveDeployer.deployInternal(ArchiveDeployer.java:83)
	at org.jboss.as.arquillian.container.ArchiveDeployer.deployInternal(ArchiveDeployer.java:64)
	at org.jboss.as.arquillian.container.ArchiveDeployer.deploy(ArchiveDeployer.java:46)
	at org.jboss.as.arquillian.container.CommonDeployableContainer.deploy(CommonDeployableContainer.java:146)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$3.call(ContainerDeployController.java:161)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$3.call(ContainerDeployController.java:128)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.executeOperation(ContainerDeployController.java:271)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.deploy(ContainerDeployController.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.container.impl.client.container.DeploymentExceptionHandler.verifyExpectedExceptionDuringDeploy(DeploymentExceptionHandler.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.container.impl.client.ContainerDeploymentContextHandler.createContainerContext(ContainerDeploymentContextHandler.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.container.impl.client.ContainerDeploymentContextHandler.createDeploymentContext(ContainerDeploymentContextHandler.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:135)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:115)
	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$1.perform(ContainerDeployController.java:95)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$1.perform(ContainerDeployController.java:80)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.forEachDeployment(ContainerDeployController.java:263)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.forEachManagedDeployment(ContainerDeployController.java:239)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.deployManaged(ContainerDeployController.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:135)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:115)
	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.execute(ContainerEventController.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:135)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:115)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeClass(EventTestRunnerAdaptor.java:80)
	at org.jboss.arquillian.testng.Arquillian.arquillianBeforeClass(Arquillian.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
Caused by: java.io.IOException: Invalid response
	at org.xnio.http.HttpUpgradeParser.parseVersion(HttpUpgradeParser.java:157)
	at org.xnio.http.HttpUpgradeParser.parse(HttpUpgradeParser.java:55)
	at org.xnio.http.HttpUpgrade$HttpUpgradeState$UpgradeResultListener.handleEvent(HttpUpgrade.java:419)
	at org.xnio.http.HttpUpgrade$HttpUpgradeState$UpgradeResultListener.handleEvent(HttpUpgrade.java:400)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:559)
	at ...asynchronous invocation...(Unknown Source)
	at org.jboss.remoting3.EndpointImpl.doConnect(EndpointImpl.java:294)
	at org.jboss.remoting3.EndpointImpl.doConnect(EndpointImpl.java:275)
	at org.jboss.remoting3.EndpointImpl.connect(EndpointImpl.java:379)
	at org.jboss.remoting3.EndpointImpl.connect(EndpointImpl.java:367)
	at org.jboss.as.protocol.ProtocolConnectionUtils.connect(ProtocolConnectionUtils.java:78)
	at org.jboss.as.protocol.ProtocolConnectionUtils.connectSync(ProtocolConnectionUtils.java:109)
	at org.jboss.as.protocol.ProtocolConnectionManager$EstablishingConnection.connect(ProtocolConnectionManager.java:256)
	at org.jboss.as.protocol.ProtocolConnectionManager.connect(ProtocolConnectionManager.java:70)
	at org.jboss.as.protocol.mgmt.FutureManagementChannel$Establishing.getChannel(FutureManagementChannel.java:204)
	at org.jboss.as.controller.client.impl.RemotingModelControllerClient.getOrCreateChannel(RemotingModelControllerClient.java:148)
	at org.jboss.as.controller.client.impl.RemotingModelControllerClient$1.getChannel(RemotingModelControllerClient.java:67)
	at org.jboss.as.protocol.mgmt.ManagementChannelHandler.executeRequest(ManagementChannelHandler.java:117)
	at org.jboss.as.protocol.mgmt.ManagementChannelHandler.executeRequest(ManagementChannelHandler.java:92)
	at org.jboss.as.controller.client.impl.AbstractModelControllerClient.executeRequest(AbstractModelControllerClient.java:236)
	at org.jboss.as.controller.client.impl.AbstractModelControllerClient.execute(AbstractModelControllerClient.java:141)
	at org.jboss.as.controller.client.impl.AbstractModelControllerClient.executeAsync(AbstractModelControllerClient.java:101)
	at org.jboss.as.controller.client.helpers.standalone.impl.ModelControllerClientServerDeploymentManager.executeOperation(ModelControllerClientServerDeploymentManager.java:50)
	at org.jboss.as.controller.client.helpers.standalone.impl.AbstractServerDeploymentManager.execute(AbstractServerDeploymentManager.java:79)
	at org.jboss.as.controller.client.helpers.standalone.ServerDeploymentHelper.deploy(ServerDeploymentHelper.java:54)
	at org.jboss.as.arquillian.container.ArchiveDeployer.deployInternal(ArchiveDeployer.java:77)
	... 103 more
]]>
            </full-stacktrace>
          </exception> <!-- org.jboss.arquillian.container.spi.client.container.DeploymentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- arquillianBeforeClass -->
        <test-method status="SKIP" signature="arquillianBeforeTest(java.lang.reflect.Method)[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84]" name="arquillianBeforeTest" is-config="true" duration-ms="0" started-at="2016-02-11T21:16:53Z" finished-at="2016-02-11T21:16:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- arquillianBeforeTest -->
        <test-method status="SKIP" signature="testCreateAuthor()[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84]" name="testCreateAuthor" duration-ms="3" started-at="2016-02-11T21:16:53Z" finished-at="2016-02-11T21:16:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateAuthor -->
        <test-method status="PASS" signature="arquillianAfterTest(java.lang.reflect.Method)[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84]" name="arquillianAfterTest" is-config="true" duration-ms="2" started-at="2016-02-11T21:16:53Z" finished-at="2016-02-11T21:16:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.softserveinc.booklibrary.test.manager.AuthorManagerTest.testCreateAuthor() throws com.softserveinc.booklibrary.exception.AuthorManagerException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- arquillianAfterTest -->
        <test-method status="SKIP" signature="testNegativeCreateAuthor(com.softserveinc.booklibrary.model.entity.Author)[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84]" name="testNegativeCreateAuthor" duration-ms="0" started-at="2016-02-11T21:16:53Z" data-provider="negativeCreateAuthorDataProvider" depends-on-methods="com.softserveinc.booklibrary.test.manager.AuthorManagerTest.testCreateAuthor" finished-at="2016-02-11T21:16:53Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AuthorManagerTest.testNegativeCreateAuthor(com.softserveinc.booklibrary.model.entity.Author)[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AuthorManagerTest.testNegativeCreateAuthor(com.softserveinc.booklibrary.model.entity.Author)[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNegativeCreateAuthor -->
        <test-method status="SKIP" signature="testDeleteAuthor()[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84]" name="testDeleteAuthor" duration-ms="0" depends-on-groups="createAuthor" started-at="2016-02-11T21:16:53Z" finished-at="2016-02-11T21:16:53Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AuthorManagerTest.testDeleteAuthor()[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84] depends on not successfully finished methods in group "createAuthor"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AuthorManagerTest.testDeleteAuthor()[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84] depends on not successfully finished methods in group "createAuthor"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteAuthor -->
        <test-method status="SKIP" signature="testNegativeDeleteAuthor(java.lang.String)[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84]" name="testNegativeDeleteAuthor" duration-ms="0" started-at="2016-02-11T21:16:53Z" data-provider="negativeDeleteAuthorDataProvider" depends-on-methods="com.softserveinc.booklibrary.test.manager.AuthorManagerTest.testDeleteAuthor" finished-at="2016-02-11T21:16:53Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AuthorManagerTest.testNegativeDeleteAuthor(java.lang.String)[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AuthorManagerTest.testNegativeDeleteAuthor(java.lang.String)[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNegativeDeleteAuthor -->
        <test-method status="SKIP" signature="testNegativeDeleteAuthorWithNoBooks()[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84]" name="testNegativeDeleteAuthorWithNoBooks" duration-ms="0" started-at="2016-02-11T21:16:53Z" depends-on-methods="com.softserveinc.booklibrary.test.manager.AuthorManagerTest.testDeleteAuthor" finished-at="2016-02-11T21:16:53Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AuthorManagerTest.testNegativeDeleteAuthorWithNoBooks()[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AuthorManagerTest.testNegativeDeleteAuthorWithNoBooks()[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNegativeDeleteAuthorWithNoBooks -->
        <test-method status="SKIP" signature="testBulkDeleteAuthor()[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84]" name="testBulkDeleteAuthor" duration-ms="0" started-at="2016-02-11T21:16:53Z" depends-on-methods="com.softserveinc.booklibrary.test.manager.AuthorManagerTest.testNegativeDeleteAuthorWithNoBooks" finished-at="2016-02-11T21:16:53Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AuthorManagerTest.testBulkDeleteAuthor()[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AuthorManagerTest.testBulkDeleteAuthor()[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBulkDeleteAuthor -->
        <test-method status="SKIP" signature="testNegativeBulkDeleteAuthors()[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84]" name="testNegativeBulkDeleteAuthors" duration-ms="0" started-at="2016-02-11T21:16:53Z" depends-on-methods="com.softserveinc.booklibrary.test.manager.AuthorManagerTest.testBulkDeleteAuthor" finished-at="2016-02-11T21:16:53Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AuthorManagerTest.testNegativeBulkDeleteAuthors()[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AuthorManagerTest.testNegativeBulkDeleteAuthors()[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNegativeBulkDeleteAuthors -->
        <test-method status="SKIP" signature="testUpdateAuthor()[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84]" name="testUpdateAuthor" duration-ms="0" depends-on-groups="updateAuthor" started-at="2016-02-11T21:16:53Z" finished-at="2016-02-11T21:16:53Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AuthorManagerTest.testUpdateAuthor()[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84] depends on not successfully finished methods in group "updateAuthor"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AuthorManagerTest.testUpdateAuthor()[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84] depends on not successfully finished methods in group "updateAuthor"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateAuthor -->
        <test-method status="SKIP" signature="testNegativeUpdateAuthor(com.softserveinc.booklibrary.model.entity.Author)[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84]" name="testNegativeUpdateAuthor" duration-ms="0" started-at="2016-02-11T21:16:53Z" data-provider="negativeUpdateAuthorDataProvider" depends-on-methods="com.softserveinc.booklibrary.test.manager.AuthorManagerTest.testUpdateAuthor" finished-at="2016-02-11T21:16:53Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AuthorManagerTest.testNegativeUpdateAuthor(com.softserveinc.booklibrary.model.entity.Author)[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AuthorManagerTest.testNegativeUpdateAuthor(com.softserveinc.booklibrary.model.entity.Author)[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNegativeUpdateAuthor -->
        <test-method status="PASS" signature="arquillianAfterClass()[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84]" name="arquillianAfterClass" is-config="true" duration-ms="106" started-at="2016-02-11T21:16:53Z" finished-at="2016-02-11T21:16:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- arquillianAfterClass -->
        <test-method status="PASS" signature="arquillianAfterSuite()[pri:0, instance:com.softserveinc.booklibrary.test.manager.AuthorManagerTest@67205a84]" name="arquillianAfterSuite" is-config="true" duration-ms="24" started-at="2016-02-11T21:16:53Z" finished-at="2016-02-11T21:16:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- arquillianAfterSuite -->
      </class> <!-- com.softserveinc.booklibrary.test.manager.AuthorManagerTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
